### ISSUE TITLE
Exception when plotting after experiment

### ISSUE THREAD

**Issue by cdelzotti** [tbarbette/npf#53] opened 2024-03-12 13:59 UTC
I'm currently trying to run this command :

`python3 /usr/local/bin/npf-run.py local --test ./script.npf --graph-filename ./results/graph.pdf  --variables LIMIT_TIME=14 --cluster client=$CLIENT server=$SERVER --graph-size 12 10 --single-output ./results/out.csv --cluster-autosave --result-path ./results/`

With the following variables in script.npf :

```shell
%variables
CPU=[1-1]
WL=1000
FREQ={1000,2000,3000,3900}
TIME=10

GEN_THREADS=8
GEN_BURST=8
GEN_RX_THREADS=8
GEN_FLOWSIZE=32

SLEEP_MODE={sleep_mode1,sleep_mode2,sleep_mode3}
SLEEP_DELTA={1,2,4,8,16,32}
GEN_RATE={4000000}
BURST_SIZE={32}
GEN_LENGTH=64
MINFREQ=1000
LIMIT=1000000000

FASTCLICK_PATH=/root/fastclick_sleep_modes/

%config
n_runs=5
results_expect={WATT,RAM,THROUGHPUT,PPS}
graph_filter_by={WATT:DROPPEDPC>0.01,MAXWATT:DROPPEDPC>0.01,LAT99:DROPPEDPC>0.01}
accept_zero={BEGIN_POLL,BEGIN_C1,BEGIN_C1E,BEGIN_C6,END_POLL,END_C1,END_C1E,END_C6}
...
[Experiment descriptions]
...

%import@client fastclick-play-single-mt
```
While the (in my case very long) testing happens without any issue, npf crashes afterwards during what seems to be the plotting phase. This is the python stack that appears :

```python
ERROR: When trying to export serie local:
Traceback (most recent call last):
  File "/usr/local/bin/npf-run.py", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/npf_run.py", line 262, in main
    grapher.graph(series=[(test, build, all_results)] + g_series,
  File "/usr/local/lib/python3.10/dist-packages/npf/grapher.py", line 706, in graph
    raise(e)
  File "/usr/local/lib/python3.10/dist-packages/npf/grapher.py", line 703, in graph
    all_results_df = pd.concat([all_results_df,x_df],ignore_index = True, axis=0)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/concat.py", line 393, in concat
    return op.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/concat.py", line 678, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3882, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```
Is there a solution to that problem ? :smiley:

**Comment by tbarbette** [comment] 2024-03-14 08:16
This is in the CSV export. Could you printf at line 703 all_results_df and x_df ? It's hard to judge the problem without the shape of your experiment.

**Comment by cdelzotti** [comment] 2024-03-14 11:02
The problem might be related to the fact that there are two columns called 'SLEEP_MODE' in `x_df`

**Comment by tbarbette** [comment] 2024-03-14 13:03
Normally duplicated results get mixed. By default there will be two results per run, which should be fine. You can also add result_add={SLEEP_MODE} in the config so the resutls are additionned instead of duplicated.

Maybe the problem comes from SLEEP_MODE not being numeric? Or one of them is empty?

**Comment by cdelzotti** [comment] 2024-03-14 15:32
SLEEP_MODE was actually both a numeric value and a label because of my dependency messing with my script. But it works like a charm now.

**Comment by tbarbette** [comment] 2024-03-16 12:22
Can you help me reproduce the problem ?
python3 npf-run.py --test integration/warnmultiple.npf --csv local.csv --force-retest

integration/warnmultiple.npf:
```
%variables
TEST={A,B,C}

%script
echo "RESULT-TEST 78"
echo "RESULT-TEST MODE
```
Definitely there is multiple warnings that should happen and I'll work on that, but I don't have a crash.

Warnings to add : 

  * RESULT-TEST MODE is ignored, probably because it's a label and can't be appended to 78
  * The pandas version I use don't complain about having two columns named "TEST" because it's both the name of a feature and a target, but it should raise a red warning as it's asking for trouble.

**Comment by tbarbette** [comment] 2024-06-26 08:34
Fixed in last push. There are now warnings to prevent this situation.

**Closed by tbarbette** 2024-06-26 08:34 UTC
